CREATE DATABASE IF NOT EXISTS booksdb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE booksdb;

CREATE TABLE IF NOT EXISTS AUTHOR (
  AUTHOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  NATIONALITY VARCHAR(100) NULL,
  CONSTRAINT UK_AUTHOR_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS CATEGORY (
  CATEGORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  CONSTRAINT UK_CATEGORY_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS BOOK (
  BOOK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(255) NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,
  PUBLISHER VARCHAR(255) NULL,
  PUBLISHED_YEAR INT NULL,
  ISBN VARCHAR(32) NULL,
  PRICE DECIMAL(12,2) NULL,
  STOCK INT NOT NULL DEFAULT 0,
  STATUS ENUM('AVAILABLE','UNAVAILABLE') NOT NULL DEFAULT 'AVAILABLE',
  INDEX IX_BOOK_TITLE (TITLE),
  INDEX IX_BOOK_AUTHOR (AUTHOR_ID),
  INDEX IX_BOOK_CATEGORY (CATEGORY_ID),
  CONSTRAINT UK_BOOK_ISBN UNIQUE (ISBN),
  CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_BOOK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS MEMBER (
  MEMBER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FULL_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PHONE VARCHAR(30) NULL,
  STATUS ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS LOAN (
  LOAN_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  BOOK_ID BIGINT NOT NULL,
  MEMBER_ID BIGINT NOT NULL,
  BORROW_DATE DATETIME NOT NULL,
  DUE_DATE DATETIME NOT NULL,
  RETURN_DATE DATETIME NULL,
  STATUS ENUM('BORROWED','OVERDUE','RETURNED') NOT NULL DEFAULT 'BORROWED',
  FINE_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  INDEX IX_LOAN_MEMBER (MEMBER_ID, STATUS),
  INDEX IX_LOAN_BOOK (BOOK_ID, STATUS),
  INDEX IX_LOAN_DUE (DUE_DATE, STATUS),
  CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_LOAN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS NOTIFICATION (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  MEMBER_ID BIGINT NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  SUBJECT VARCHAR(255) NOT NULL,
  BODY TEXT NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PROCESS_ID VARCHAR(36) NULL,
  RETRY_COUNT INT NOT NULL DEFAULT 0,
  LOCKED_AT DATETIME NULL,
  TIMEOUT_SEC INT NOT NULL DEFAULT 300,
  LAST_ERROR TEXT NULL,
  LAST_ATTEMPT_AT DATETIME NULL,
  INDEX IX_NOTIFICATION_PROCESS (PROCESS_ID),
  INDEX IX_NOTIFICATION_LOCK (LOCKED_AT),
  INDEX IX_NOTIFICATION_RETRY (RETRY_COUNT)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION_HISTORY (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  MEMBER_ID BIGINT NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  SUBJECT VARCHAR(255) NOT NULL,
  BODY TEXT NOT NULL,
  SUCCESS BOOLEAN NOT NULL,
  ERROR_MESSAGE TEXT NULL,
  CREATED_AT DATETIME NOT NULL,
  ARCHIVED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX IX_NH_CREATED (CREATED_AT, SUCCESS)
);
